version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: argus_dev
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  
  web:
    build: .
    command: mix phx.server
    environment:
      MIX_ENV: dev
      DATABASE_URL: ecto://postgres:postgres@postgres/argus_dev
    ports:
      - "4000:4000"
    depends_on:
      - postgres
    volumes:
      - .:/app
      - deps:/app/deps
      - _build:/app/_build
    stdin_open: true
    tty: true

volumes:
  pgdata:
  deps:
  _build: